name: luthien-labs-frontend

services:
  app:
    build:
      context: .
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_API_KEY: ${PUBLIC_API_KEY}
    ports:
      - "3002:80"
    restart: always